### ISSUE TITLE
Issue with the basic tutorial and get_lagged_dependencies function

### ISSUE THREAD

**Issue by ThomasAuriel** [jakobrunge/tigramite#282]
Using the example from the [tutorial](https://github.com/jakobrunge/tigramite/blob/master/tutorials/tigramite_tutorial_basics.ipynb) i got the wanted outputs.

How if I try to add my own values :
```python
date = list(generation.dataframe.index.values)
var_names=list(generation.dataframe.columns.values)
dataframe = pp.DataFrame(data=np.array(generation.dataframe), datatime={0:np.arange(len(date))}, vector_vars=var_names)
```

I got an issue at:
```python
correlations = pcmci.get_lagged_dependencies(tau_max=20, val_only=True)['val_matrix']
```

with the error message:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/auriel/.conda/envs/botelectricity/lib/python3.10/site-packages/tigramite/pcmci.py", line 1316, in get_lagged_dependencies
    return self._run_mci_or_variants(
  File "/home/auriel/.conda/envs/botelectricity/lib/python3.10/site-packages/tigramite/pcmci.py", line 1124, in _run_mci_or_variants
    val = self.cond_ind_test.get_measure(X, Y, Z=Z, tau_max=tau_max)
  File "/home/auriel/.conda/envs/botelectricity/lib/python3.10/site-packages/tigramite/independence_tests/independence_tests_base.py", line 588, in get_measure
    array, xyz, (X, Y, Z) = self._get_array(X, Y, Z, tau_max)
  File "/home/auriel/.conda/envs/botelectricity/lib/python3.10/site-packages/tigramite/independence_tests/independence_tests_base.py", line 268, in _get_array
    return self.dataframe.construct_array(X=X, Y=Y, Z=Z,
  File "/home/auriel/.conda/envs/botelectricity/lib/python3.10/site-packages/tigramite/data_processing.py", line 647, in construct_array
    X = vectorize(X)
  File "/home/auriel/.conda/envs/botelectricity/lib/python3.10/site-packages/tigramite/data_processing.py", line 643, in vectorize
    for (vector_var, vector_lag) in self.vector_vars[var]:
ValueError: not enough values to unpack (expected 2, got 1)
````

And the plot `tp.plot_timeseries(dataframe)` does not show the variables names but only a number sequence (from 1 to 11).

The different elements have the same dimension : 
- dataframe length is 25*11
- datetime length is 25
- columns names length is 11

**Comment by sagarsimha** [comment]
Hi. 
1. I would suspect that the issue in dimensionality mismatch stems from passing (what seems to be) pandas dataframe onto tigramite dataframe. Can you ensure that the numpy array you are passing onto tigramite dataframe is of shape (observations T, variables N)?
2. datatime={0:np.arange(len(date))} is producing a dictionary of the kind {0: array([0, 1, 2, 3, 4, 5, 6, 7, 8,...])}. It has to be an array.
3. tp.plot_timeseries(dataframe) plots and shows the variable names according to what was passed into var_names while creating the tigramite dataframe. var_names=list(generation.dataframe.columns.values) seem to pass number sequences. Please also check this!
Look into this docstring for the parameters and their datatypes,
https://github.com/jakobrunge/tigramite/blob/c877f0b578c357b1c26f666764be07676193d4dc/tigramite/data_processing.py#L19

**Comment by jakobrunge** [comment]
Did this help?
