### ISSUE TITLE
Relative import is broken for CMIknn

### ISSUE THREAD

**Issue by yegorborisov** [jakobrunge/tigramite#429]
Hi, apparently, a relative import is missing in the tigramite/independence_tests/cmiknn.py:

from tigramite.independence_tests.cmiknn import CMIknn
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/pydevconsole.py", line 364, in runcode
    coro = func()
  File "<input>", line 1, in <module>
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/eborisov/PycharmProject/vertex-pre-built-containers/venv/lib/python3.9/site-packages/tigramite/independence_tests/cmiknn.py", line 10, in <module>
    from independence_tests_base import CondIndTest
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'independence_tests_base'

getting it with the latest 5.2.6.4 version.

**Comment by jakobrunge** [comment]
Fixed in Master and pip (in few minutes). Thanks!
