### ISSUE TITLE
KeyError prevents plotting TimeSeries Graph?  

### ISSUE THREAD

**Issue by ZackKaufman** [jakobrunge/tigramite#50]
Dear Dr. Runge & Contributors, 

I am trying to utilize the tigramite.plotting package to visualize the time-series graph (plot_timeseries_graph and  plot_mediation_time_series_graph). Whether I am using my own code or copying your notebook tutorial, I consistently am stopped by this error: 

```
tp.plot_mediation_time_series_graph(var_names=var_names,path_node_array=graph_data['path_node_array'],tsg_path_val_matrix=graph_data['tsg_path_val_matrix'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/zskaufma/.conda/envs/env_tigramite/lib/python3.6/site-packages/tigramite/plotting.py", line 2023, in plot_mediation_time_series_graph
    network_lower_bound=network_lower_bound
  File "/home/zskaufma/.conda/envs/env_tigramite/lib/python3.6/site-packages/tigramite/plotting.py", line 1126, in _draw_network_with_curved_edges
    seen[(u, v)] = draw_edge(ax, u, v, d, seen, arrowstyle, directed=True)
  File "/home/zskaufma/.conda/envs/env_tigramite/lib/python3.6/site-packages/tigramite/plotting.py", line 827, in draw_edge
    if d['directed_attribute'] == 'spurious':
KeyError: 'directed_attribute
```
The meaning of this is not particularly clear to me, so any help would be much appreciated. Note that this problem is specific to the visualization commands referenced above; plot_timeseries and plot_graph work fine for me. 

Best regards,
Zack K

**Comment by jakobrunge** [comment]
Thanks for spotting this. It's due to an API change in networkx. Checkout the developer branch of tigramite, there it should be fixed. This branch will be released very soon.
