### ISSUE TITLE
Tigramite cython issues

### ISSUE THREAD

**Issue by 27Topquark** [jakobrunge/tigramite#71]
When I try to install on my Windows 10 system (Pycharm virtual env) I get the following error messages:

Traceback (most recent call last):
  File "D:\\Abhinav_Sharma\\Software\\tigramite-master\\setup.py", line 72, in <module>
    EXT_MODULES += define_extension("tigramite.tigramite_cython_code")
  File "D:\\Abhinav_Sharma\\Software\\tigramite-master\\setup.py", line 43, in define_extension
    return cythonize(Extension(extension_name, source_files))
  File "C:\venv\lib\site-packages\Cython\Build\Dependencies.py", line 974, in cythonize
    aliases=aliases)
  File "C:\venv\lib\site-packages\Cython\Build\Dependencies.py", line 817, in create_extension_list
    for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
  File "C:\venv\lib\site-packages\Cython\Build\Dependencies.py", line 116, in nonempty
    raise ValueError(error_msg)
ValueError: 'tigramite/tigramite_cython_code.pyx' doesn't match any files

**Comment by pingenglj** [comment]
@27Topquark Did you resolve this issue? I'm running into the same error, could you share your solution?

EDIT: Installation in WSL seems to be no problem.
